#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

[ -e /tmp/"CloudBerry Backup"/CBB_COMMAND.sock ]
[ -e /tmp/"CloudBerry Backup"/CBB_CONFIG.sock ]
[ -e /tmp/"CloudBerry Backup"/CBB_NOTIFICATION.sock ]
[ -e /tmp/"CloudBerry Backup"/CBB_REPLY.sock ]

# vim:ts=4:sw=4:et:sts=4
