#!/usr/bin/with-contenv sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

# Wait for dependent services to be up and running.
s6-waitdeps

echo "Starting CloudBerry Backup service..."
exec $APP_NICE_CMD /opt/local/"CloudBerry Backup"/bin/cbbLocalManagement

# vim: set ft=sh :
