#!/usr/bin/with-contenv sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

echo "Starting CloudBerry Backup service..."
exec /opt/local/"CloudBerry Backup"/bin/cbbLocalManagement

# vim: set ft=sh :
