#!/usr/bin/with-contenv sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

echo "[$(basename "$(pwd)")] starting..."
exec $APP_NICE_CMD /opt/local/"CloudBerry Backup"/bin/cbbLocalManagement

# vim: set ft=sh :
