#!/usr/bin/with-contenv sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

# Wait for dependent services to be up and running.
s6-waitdeps

echo "Starting CloudBerry Backup service..."
exec 2>&1 $APP_NICE_CMD s6-setuidgid $USER_ID:$GROUP_ID /opt/local/"CloudBerry Backup"/bin/cbbWebAccess >> /config/logs/log_WebAccess_output.log

# vim: set ft=sh :
