#!/usr/bin/with-contenv sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

echo "[$(basename "$(pwd)")] starting..."
exec 2>&1 $APP_NICE_CMD s6-applyuidgid -u $USER_ID -g $GROUP_ID -G ${SUP_GROUP_IDS:-$GROUP_ID} /opt/local/"CloudBerry Backup"/bin/cbbWebAccess >> /config/"Online Backup"/00000000-0000-0000-0000-000000000000/logs/log_WebAccess_output.log

# vim: set ft=sh :
